version: '3.8'

services:
  motus1:
    build:
      context: ./motus/.
      dockerfile: Dockerfile
    container_name: "motus1" # Utilisation d'une variable d'environnement pour le port
    ports:
      - "3005:3005"
    volumes:
      - motus_data1:/data
    environment:
      - PORT=3005  # Définir la variable d'environnement PORT avec une valeur par défaut

  motus2:
    build:
      context: ./motus/.
      dockerfile: Dockerfile
    container_name: "motus2" # Utilisation d'une variable d'environnement pour le port
    ports:
      - "3006:3006"
    volumes:
      - motus_data2:/data
    environment:
      - PORT=3006  # Définir la variable d'environnement PORT avec une valeur par défaut
  
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  score1:
    depends_on:
      - redis
    build:
      context: ./score-motus/.
      dockerfile: Dockerfile
    container_name: "score1"
    ports:
      - "3008:3008"
    volumes:
      - score_motus_data1:/data
    environment:
      - PORT=3008

  score2:
    depends_on:
      - redis
    build:
      context: ./score-motus/.
      dockerfile: Dockerfile
    container_name: "score2"
    ports:
      - "3009:3009"
    volumes:
      - score_motus_data2:/data
    environment:
      - PORT=3009
  
  haproxy:
    depends_on:
      - motus1
      - motus2
    build:
      context: ./haproxy/.
      dockerfile: Dockerfile
    container_name: "haproxy"
    ports:
      - "3100:3100"
      - "3007:3007"
      - "9090:9090"

volumes:
  motus_data1:
  motus_data2:
  score_motus_data1:
  score_motus_data2:
  redis_data: